name: customname
version: '0.0.2'
main: me.axicavlo.customname.Customname
api-version: '1.21'
depend: [ProtocolLib]
commands:
  customname:
    description: 플레이어의 닉네임을 설정합니다.
    usage: /customname [이름]

